from __future__ import annotations

from pathlib import Path

DEFAULT_CONTROL_DT = 0.02
DEFAULT_BALL_HEIGHT = 0.28
DEFAULT_VIEWER_RESET_HEIGHT = 0.30

DEFAULT_ACTION_LIMIT = 0.03
DEFAULT_MAX_EPISODE_STEPS = 300
DEFAULT_SUCCESS_VELOCITY_THRESHOLD = 0.5

DEFAULT_BOUNCE_EPISODES = 5
DEFAULT_BOUNCE_MAX_STEPS = 1200
DEFAULT_KEEPUP_EPISODES = 5
DEFAULT_KEEPUP_MAX_STEPS = 1500
DEFAULT_KEEPUP_PREVIEW_TIME = 0.10
DEFAULT_ANALYSIS_EPISODES = 5
DEFAULT_ANALYSIS_PREFIX = "ee_rollout_analysis"

DEFAULT_PPO_TOTAL_TIMESTEPS = 10_000
DEFAULT_PPO_N_STEPS = 256
DEFAULT_PPO_BATCH_SIZE = 64
DEFAULT_PPO_LEARNING_RATE = 3.0e-4
DEFAULT_PPO_GAMMA = 0.99
DEFAULT_PPO_RUN_NAME = "ppo_active_hit"

SMOKE_PPO_TOTAL_TIMESTEPS = 256
SMOKE_PPO_N_STEPS = 64
SMOKE_PPO_BATCH_SIZE = 32
SMOKE_PPO_RUN_NAME = "ppo_smoke"


def default_ppo_model_candidates(ppo_runs_root: Path) -> list[Path]:
    return [
        ppo_runs_root / DEFAULT_PPO_RUN_NAME / f"{DEFAULT_PPO_RUN_NAME}_model.zip",
        ppo_runs_root / SMOKE_PPO_RUN_NAME / f"{SMOKE_PPO_RUN_NAME}_model.zip",
    ]
