from __future__ import annotations

DEFAULT_CONTROL_DT = 0.02
DEFAULT_MAX_EPISODE_STEPS = 1200

DEFAULT_TARGET_APEX_HEIGHT = 0.24
DEFAULT_MIN_USEFUL_APEX_HEIGHT = 0.10
DEFAULT_MAX_USEFUL_APEX_HEIGHT = 0.44
DEFAULT_APEX_XY_TOLERANCE = 0.14

DEFAULT_RESET_XY_RANGE = 0.07
DEFAULT_RESET_HEIGHT_JITTER = 0.04
DEFAULT_RESET_VELOCITY_XY_RANGE = 0.08
DEFAULT_RESET_VELOCITY_Z_RANGE = (-0.35, -0.05)
DEFAULT_RESET_SPIN_RANGE = 20.0

DEFAULT_PPO_TOTAL_TIMESTEPS = 2_000_000
DEFAULT_PPO_N_STEPS = 512
DEFAULT_PPO_BATCH_SIZE = 512
DEFAULT_PPO_LEARNING_RATE = 2.0e-4
DEFAULT_PPO_GAMMA = 0.995
DEFAULT_PPO_GAE_LAMBDA = 0.95
DEFAULT_PPO_CLIP_RANGE = 0.15
DEFAULT_PPO_ENT_COEF = 0.002
DEFAULT_PPO_LOG_STD_INIT = -3.0
