from __future__ import annotations

from pathlib import Path

# MuJoCo 제어 주기와 KeepUp 환경의 기본 물리/종료 기준을 한곳에 둔다.
# LINK: pingpong_rl2/src/pingpong_rl2/envs/keepup_env.py:53
DEFAULT_CONTROL_DT = 0.02
DEFAULT_BALL_HEIGHT = 0.50
DEFAULT_ACTION_LIMIT = 0.04
DEFAULT_MAX_EPISODE_STEPS = 600
DEFAULT_SUCCESS_VELOCITY_THRESHOLD = 0.5

# reset 분포 기본값은 CLI, curriculum, 재현 평가가 같은 초기 조건을 공유하도록 맞춘다.
# LINK: pingpong_rl2/src/pingpong_rl2/training/env_config.py:96
DEFAULT_RESET_XY_RANGE = 0.06
DEFAULT_RESET_BALL_HEIGHT_RANGE = 0.0
DEFAULT_RESET_VELOCITY_XY_RANGE = 0.01
DEFAULT_RESET_VELOCITY_Z_RANGE = (-0.02, 0.01)

# reward 기본 가중치는 별도 preset이 없을 때 env 생성자가 그대로 사용하는 기준선이다.
DEFAULT_TRACKING_REWARD_WEIGHT = 0.6
DEFAULT_CONTACT_BONUS = 4.0
DEFAULT_APEX_MATCH_REWARD_WEIGHT = 2.0
DEFAULT_FLOOR_PENALTY = -8.0
DEFAULT_BODY_CONTACT_PENALTY = -10.0
DEFAULT_FAILURE_PENALTY = -5.0

# bounce sanity 스크립트에서 학습 없이 물리 동작만 빠르게 확인할 때 쓰는 기본 반복 수다.
DEFAULT_BOUNCE_EPISODES = 5
DEFAULT_BOUNCE_MAX_STEPS = 1200

# PPO 기본 하이퍼파라미터와 action_mode별 run 이름은 경로/요약 파일 이름의 기준이 된다.
# LINK: pingpong_rl2/src/pingpong_rl2/utils/ppo_runs.py:41
DEFAULT_PPO_TOTAL_TIMESTEPS = 20_000
DEFAULT_PPO_N_STEPS = 256
DEFAULT_PPO_BATCH_SIZE = 256
DEFAULT_PPO_LEARNING_RATE = 3.0e-4
DEFAULT_PPO_GAMMA = 0.99
DEFAULT_PPO_RUN_NAME = "pmk"
DEFAULT_PPO_POSITION_STRIKE_RUN_NAME = "pmk_s"
DEFAULT_PPO_POSITION_TILT_RUN_NAME = "pmk_t"
DEFAULT_PPO_POSITION_STRIKE_TILT_RUN_NAME = "pmk_st"
DEFAULT_PPO_POSITION_STRIKE_TILT_LIFT_RUN_NAME = "pmk_stl"
DEFAULT_PPO_POSITION_CONTACT_FRAME_RUN_NAME = "pmk_cf"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_RESIDUAL_RUN_NAME = "pmk_cfvr"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_RESIDUAL_RUN_NAME = "pmk_cfvtr"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_RESIDUAL_RUN_NAME = "pmk_cfvtlr"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_RESIDUAL_RUN_NAME = "pmk_cfvtlar"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_TRACKING_RESIDUAL_RUN_NAME = "pmk_cfvtlatr"

# smoke run은 전체 파이프라인 검사용이라 이름과 rollout 크기를 작게 분리한다.
# LINK: pingpong_rl2/scripts/run_ppo_learning.py:70
SMOKE_PPO_TOTAL_TIMESTEPS = 1_024
SMOKE_PPO_N_STEPS = 64
SMOKE_PPO_BATCH_SIZE = 64
SMOKE_PPO_RUN_NAME = "pmk_smoke"
SMOKE_PPO_POSITION_STRIKE_RUN_NAME = "pmk_s_smoke"
SMOKE_PPO_POSITION_TILT_RUN_NAME = "pmk_t_smoke"
SMOKE_PPO_POSITION_STRIKE_TILT_RUN_NAME = "pmk_st_smoke"
SMOKE_PPO_POSITION_STRIKE_TILT_LIFT_RUN_NAME = "pmk_stl_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_RUN_NAME = "pmk_cf_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_RESIDUAL_RUN_NAME = "pmk_cfvr_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_RESIDUAL_RUN_NAME = "pmk_cfvtr_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_RESIDUAL_RUN_NAME = "pmk_cfvtlr_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_RESIDUAL_RUN_NAME = "pmk_cfvtlar_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_TRACKING_RESIDUAL_RUN_NAME = "pmk_cfvtlatr_smoke"

LEGACY_PPO_RUN_NAMES = (
    "ppo_minimal_keepup",
    "ppo_position_tilt_keepup",
    "ppo_smoke",
    "ppo_position_tilt_smoke",
)


def default_ppo_model_candidates(ppo_runs_root: Path) -> list[Path]:
    # 명시 모델이 없을 때 최신 기본 action_mode 이름부터 legacy 이름까지 순서대로 탐색한다.
    # LINK: pingpong_rl2/src/pingpong_rl2/utils/ppo_runs.py:144
    candidate_names = (
        DEFAULT_PPO_RUN_NAME,
        DEFAULT_PPO_POSITION_STRIKE_RUN_NAME,
        DEFAULT_PPO_POSITION_TILT_RUN_NAME,
        DEFAULT_PPO_POSITION_STRIKE_TILT_RUN_NAME,
        DEFAULT_PPO_POSITION_STRIKE_TILT_LIFT_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_RESIDUAL_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_RESIDUAL_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_RESIDUAL_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_RESIDUAL_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_TRACKING_RESIDUAL_RUN_NAME,
        SMOKE_PPO_RUN_NAME,
        SMOKE_PPO_POSITION_STRIKE_RUN_NAME,
        SMOKE_PPO_POSITION_TILT_RUN_NAME,
        SMOKE_PPO_POSITION_STRIKE_TILT_RUN_NAME,
        SMOKE_PPO_POSITION_STRIKE_TILT_LIFT_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_RESIDUAL_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_RESIDUAL_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_RESIDUAL_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_RESIDUAL_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_TRACKING_RESIDUAL_RUN_NAME,
        *LEGACY_PPO_RUN_NAMES,
    )
    return [ppo_runs_root / run_name / f"{run_name}_model.zip" for run_name in candidate_names]
