from __future__ import annotations

from pingpong_rl2.defaults import (
    DEFAULT_BALL_HEIGHT,
    DEFAULT_MAX_EPISODE_STEPS,
    DEFAULT_PPO_BATCH_SIZE,
    DEFAULT_PPO_LEARNING_RATE,
    DEFAULT_PPO_N_STEPS,
    DEFAULT_RESET_BALL_HEIGHT_RANGE,
    DEFAULT_RESET_VELOCITY_XY_RANGE,
    DEFAULT_RESET_VELOCITY_Z_RANGE,
    DEFAULT_RESET_XY_RANGE,
)

_UNLIMITED_EVAL_STEP_LIMIT = 3_600

_TILT_PROFILES: dict[str, dict[str, object]] = {
    "early": {
        "tilt_action_limit": 0.015,
        "target_tilt_limit": (0.06, 0.06),
        "tilt_angle_penalty_weight": 0.06,
        "tilt_action_delta_penalty_weight": 0.12,
    },
    "mid": {
        "tilt_action_limit": 0.025,
        "target_tilt_limit": (0.09, 0.09),
        "tilt_angle_penalty_weight": 0.05,
        "tilt_action_delta_penalty_weight": 0.10,
    },
    "late": {
        "tilt_action_limit": 0.035,
        "target_tilt_limit": (0.12, 0.12),
        "tilt_angle_penalty_weight": 0.04,
        "tilt_action_delta_penalty_weight": 0.08,
    },
    "final": {
        "tilt_action_limit": 0.04,
        "target_tilt_limit": (0.12, 0.12),
        "tilt_angle_penalty_weight": 0.03,
        "tilt_action_delta_penalty_weight": 0.06,
    },
}

_ENV_PRESETS: dict[str, dict[str, object]] = {
    "baseline_position": {
        "action_mode": "position",
    },
    "strike_position": {
        "action_mode": "position_strike",
    },
    "strike_velocity_obs": {
        "action_mode": "position_strike",
        "include_velocity_domain_observation": True,
    },
    "tilt_experiment": {
        "action_mode": "position_tilt",
        "tilt_profile": "auto",
    },
    "final_candidate": {
        "action_mode": "position_strike",
        "strike_tilt_ramp_pitch": -0.03,
        "strike_tilt_ramp_xy_tolerance": 0.04,
        "post_contact_return_assist_weight": 0.5,
        "post_contact_return_max_intercept_time": 0.6,
    },
    "phase_contract_candidate": {
        "action_mode": "position_strike",
        "strike_tilt_ramp_pitch": -0.03,
        "strike_tilt_ramp_xy_tolerance": 0.04,
        "post_contact_return_assist_weight": 0.5,
        "post_contact_return_max_intercept_time": 0.6,
        "include_task_phase_observation": True,
        "include_contact_context_observation": True,
        "include_next_intercept_observation": True,
        "next_intercept_reachable_bonus_weight": 0.2,
    },
    "followup_strike_candidate": {
        "action_mode": "position_strike",
        "strike_tilt_ramp_pitch": -0.03,
        "strike_tilt_ramp_xy_tolerance": 0.04,
        "followup_strike_target_tilt": (-0.03, 0.0),
        "post_contact_return_assist_weight": 0.5,
        "post_contact_return_max_intercept_time": 0.6,
        "include_task_phase_observation": True,
        "include_contact_context_observation": True,
        "include_next_intercept_observation": True,
        "next_intercept_reachable_bonus_weight": 0.2,
    },
    "contact_primitive_candidate": {
        "action_mode": "position_strike_tilt",
        "tilt_profile": "early",
        "strike_tilt_ramp_pitch": -0.06,
        "strike_tilt_ramp_xy_tolerance": 0.04,
        "followup_strike_target_tilt": (-0.06, 0.0),
        "followup_strike_lift_boost": 0.02,
        "post_contact_return_assist_weight": 0.5,
        "post_contact_return_max_intercept_time": 0.6,
        "include_task_phase_observation": True,
        "include_contact_context_observation": True,
        "include_next_intercept_observation": True,
    },
    "contact_lift_candidate": {
        "action_mode": "position_strike_tilt_lift",
        "tilt_profile": "early",
        "strike_tilt_ramp_pitch": -0.06,
        "strike_tilt_ramp_xy_tolerance": 0.04,
        "followup_strike_target_tilt": (-0.06, 0.0),
        "followup_strike_lift_boost": 0.02,
        "followup_lift_action_limit": 0.02,
        "post_contact_return_assist_weight": 0.5,
        "post_contact_return_max_intercept_time": 0.6,
        "include_task_phase_observation": True,
        "include_contact_context_observation": True,
        "include_next_intercept_observation": True,
    },
    "contact_frame_candidate": {
        "action_mode": "position_contact_frame",
        "target_ball_height": 0.20,
        "tilt_profile": "early",
        "strike_tilt_ramp_pitch": -0.06,
        "strike_tilt_ramp_xy_tolerance": 0.04,
        "followup_strike_target_tilt": (-0.06, 0.0),
        "followup_strike_contact_offset_ratio": 0.25,
        "followup_strike_contact_offset_max": 0.02,
        "contact_frame_base_strike_z_boost": 0.024,
        "contact_frame_base_strike_z_offset": 0.01,
        "contact_frame_base_tilt_residual": (-0.02, 0.0),
        "contact_frame_followthrough_gain": 1.0,
        "contact_frame_followthrough_time": 0.06,
        "contact_frame_followthrough_max": 0.04,
        "contact_frame_trajectory_tilt_gain": 1.0,
        "contact_frame_trajectory_tilt_limit": (0.0, 0.03),
        "post_contact_return_z_offset": -0.01,
        "contact_frame_action_penalty_weight": 0.2,
        "trajectory_match_reward_weight": 0.4,
        "useful_contact_return_target_xy_reward_weight": 0.25,
        "return_target_xy_tolerance": 0.12,
        "next_intercept_reachable_bonus_weight": 0.25,
        "easy_next_ball_reward_weight": 0.3,
        "log_std_init": -3.0,
        "zero_init_action_mean": True,
        "post_contact_return_assist_weight": 0.8,
        "post_contact_return_max_intercept_time": 0.6,
        "include_task_phase_observation": True,
        "include_contact_context_observation": True,
        "include_next_intercept_observation": True,
        "include_desired_outgoing_velocity_observation": True,
        "desired_outgoing_xy_mode": "next_intercept",
    },
}

_ENV_PRESETS["contact_frame_tilt_headroom_candidate"] = {
    **_ENV_PRESETS["contact_frame_candidate"],
    "target_tilt_limit": (0.09, 0.09),
    "strike_tilt_ramp_pitch": -0.04,
    "followup_strike_target_tilt": (-0.04, 0.0),
    "contact_frame_trajectory_tilt_gain": 1.0,
    "contact_frame_trajectory_tilt_limit": (0.03, 0.03),
}

_ENV_PRESETS["contact_frame_followthrough_candidate"] = {
    **_ENV_PRESETS["contact_frame_candidate"],
    "contact_frame_followthrough_gain": 1.0,
    "contact_frame_followthrough_time": 0.06,
    "contact_frame_followthrough_max": 0.04,
}

_ENV_PRESETS["contact_frame_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_candidate"],
    "n_envs": 1,
    "n_steps": 512,
    "batch_size": 256,
    "learning_rate": 1.0e-5,
    "n_epochs": 1,
    "clip_range": 0.05,
    "eval_episodes": 100,
    "reset_xy_range": 0.0,
    "reset_velocity_xy_range": 0.0,
    "reset_velocity_z_range": (-0.01, 0.01),
    "bootstrap_heuristic_episodes": 120,
    "bootstrap_min_useful_bounces": 2,
    "bootstrap_max_samples": 4_000,
    "bootstrap_epochs": 50,
    "bootstrap_batch_size": 256,
    "bootstrap_learning_rate": 1.0e-4,
    "bootstrap_sample_mode": "post_success",
}

_ENV_PRESETS["contact_frame_followup_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_bootstrap_candidate"],
    "bootstrap_followup_epochs": 20,
    "bootstrap_followup_sample_mode": "post_success_reachable",
    "bootstrap_followup_min_useful_bounces": 3,
    "bootstrap_followup_learning_rate": 5.0e-5,
}

_ENV_PRESETS["contact_frame_reachable_success_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_followup_bootstrap_candidate"],
    "require_reachable_next_intercept_for_success": True,
    "min_easy_next_ball_score_for_success": 0.0,
}

_ENV_PRESETS["contact_frame_strict_contract_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_reachable_success_bootstrap_candidate"],
    "terminate_on_nonuseful_contact": True,
}

_ENV_PRESETS["contact_frame_recovery_retract_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_reachable_success_bootstrap_candidate"],
    "post_contact_return_z_offset": -0.01,
}

_ENV_PRESETS["contact_frame_recovery_roll_retract_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_reachable_success_bootstrap_candidate"],
    "contact_frame_trajectory_tilt_gain": 1.0,
    "contact_frame_trajectory_tilt_limit": (0.0, 0.03),
    "post_contact_return_z_offset": -0.01,
}

_ENV_PRESETS["contact_frame_body_safe_offset_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_recovery_roll_retract_bootstrap_candidate"],
    "keepup_target_xy_offset": (0.0, 0.03),
}

_ENV_PRESETS["contact_frame_sweet_spot_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_recovery_roll_retract_bootstrap_candidate"],
    "reset_xy_range": 0.028,
    "reset_velocity_xy_range": 0.0,
    "reset_velocity_z_range": (-0.01, 0.01),
    "next_intercept_success_radius": 0.04,
    "easy_next_ball_xy_radius": 0.04,
}

_ENV_PRESETS["contact_frame_sweet_spot_nullspace_candidate"] = {
    **_ENV_PRESETS["contact_frame_sweet_spot_bootstrap_candidate"],
    "post_contact_return_predict_during_rise": False,
    "controller_nullspace_posture_gain": 0.20,
    "controller_nullspace_posture_max_step": 0.010,
    "controller_body_clearance_gain": 0.75,
    "controller_body_clearance_margin": 0.14,
    "controller_body_clearance_vertical_margin": 0.32,
    "controller_body_clearance_max_step": 0.018,
    "controller_body_clearance_body_names": ("link5", "link6"),
    "contact_frame_centering_tilt_limit": (0.02, 0.03),
    "contact_frame_centering_tilt_radius": 0.08,
    "contact_frame_centering_tilt_deadband": 0.01,
}

_ENV_PRESETS["contact_frame_planned_intercept_candidate"] = {
    **_ENV_PRESETS["contact_frame_sweet_spot_bootstrap_candidate"],
    "post_contact_return_predict_during_rise": False,
    "contact_frame_intercept_velocity_gain": 0.65,
    "contact_frame_intercept_velocity_max": 1.2,
    "contact_frame_intercept_velocity_time_floor": 0.08,
}

_ENV_PRESETS["contact_frame_self_rally_candidate"] = {
    **_ENV_PRESETS["contact_frame_planned_intercept_candidate"],
    "action_mode": "position_contact_frame_velocity_residual",
    "scene_path": "assets/scene.xml",
    "n_envs": 4,
    "batch_size": 512,
    "ball_height": 0.34,
    "target_ball_height": 0.30,
    "reset_ball_height_range": 0.02,
    "lateral_action_limit": 0.02,
    "vertical_action_limit": 0.030,
    "tilt_action_limit": 0.004,
    "target_tilt_limit": (0.12, 0.12),
    "strike_tilt_ramp_pitch": None,
    "followup_strike_target_tilt": None,
    "contact_frame_base_tilt_residual": None,
    "controller_orientation_gain": 1.10,
    "controller_max_orientation_step": 0.18,
    "controller_velocity_feedback_gain": 0.45,
    "controller_max_velocity_step": 0.065,
    "controller_nullspace_posture_gain": 0.20,
    "controller_nullspace_posture_max_step": 0.010,
    "controller_body_clearance_gain": 0.75,
    "controller_body_clearance_margin": 0.14,
    "controller_body_clearance_vertical_margin": 0.32,
    "controller_body_clearance_max_step": 0.018,
    "controller_body_clearance_body_names": ("link5", "link6"),
    "contact_frame_planner_enabled": True,
    "contact_frame_planner_hold_during_descent": True,
    "contact_frame_planner_min_intercept_time": 0.03,
    "contact_frame_planner_max_intercept_time": 0.60,
    "contact_frame_strike_hold_time": 0.05,
    "contact_frame_strike_hold_min_readiness": 0.60,
    "contact_frame_base_strike_z_boost": 0.028,
    "contact_frame_base_strike_z_offset": 0.010,
    "contact_frame_apex_lift_gain": 0.12,
    "contact_frame_apex_lift_max": 0.110,
    "contact_frame_low_apex_recovery_lift_gain": 0.024,
    "contact_frame_low_apex_recovery_lift_max": 0.045,
    "contact_frame_low_apex_recovery_velocity_gain": 0.28,
    "contact_frame_low_apex_recovery_velocity_max": 0.45,
    "contact_frame_velocity_lead_gain": 0.04,
    "contact_frame_velocity_lead_max": 0.025,
    "contact_frame_velocity_target_gain": 1.00,
    "contact_frame_velocity_target_max": 2.9,
    "contact_frame_velocity_scale_action_limit": 0.35,
    "contact_frame_outgoing_xy_action_limit": 0.35,
    "contact_frame_followthrough_max": 0.055,
    "contact_frame_trajectory_tilt_gain": 0.70,
    "contact_frame_trajectory_tilt_limit": (0.05, 0.05),
    "contact_frame_tilt_ramp_time": 0.35,
    "contact_frame_centering_tilt_limit": (0.035, 0.035),
    "contact_frame_centering_tilt_radius": 0.12,
    "contact_frame_centering_tilt_deadband": 0.008,
    "require_reachable_next_intercept_for_success": True,
    "require_apex_height_window_for_success": True,
    "min_easy_next_ball_score_for_success": 0.45,
    "gate_nonuseful_easy_next_ball_by_apex": True,
    "terminate_on_low_apex_contact": True,
    "low_apex_contact_height_threshold": 0.14,
    "low_apex_contact_grace_count": 3,
    "easy_next_ball_reward_weight": 1.00,
    "next_intercept_xy_error_penalty_weight": 1.35,
    "post_contact_lateral_velocity_penalty_weight": 0.75,
    "contact_xy_error_penalty_weight": 0.25,
    "contact_racket_lateral_velocity_penalty_weight": 0.45,
    "contact_racket_lateral_velocity_tolerance": 0.18,
    "max_contact_racket_lateral_speed_for_success": 0.45,
    "nonuseful_contact_penalty_weight": 0.75,
    "contact_apex_under_target_penalty_weight": 0.80,
    "contact_apex_progress_reward_weight": 0.75,
    "contact_apex_recovery_progress_reward_weight": 0.45,
    "gate_contact_apex_progress_by_easy_next_ball": True,
    "contact_apex_progress_min_easy_next_ball_score": 0.35,
    "contact_lateral_stability_reward_weight": 0.45,
    "contact_lateral_stability_speed_tolerance": 0.25,
    "contact_lateral_stability_xy_tolerance": 0.08,
    "stable_contact_reward_weight": 1.60,
    "stable_cycle_reward_weight": 1.10,
    "stable_cycle_reward_cap": 4,
    "stable_cycle_min_easy_next_ball_score": 0.45,
    "trajectory_match_reward_weight": 0.55,
    "trajectory_error_penalty_weight": 0.75,
    "reward_contact_quality_on_any_upward_contact": True,
    "bootstrap_heuristic_episodes": 80,
    "bootstrap_min_useful_bounces": 1,
    "bootstrap_max_samples": 3_000,
    "bootstrap_epochs": 20,
    "bootstrap_batch_size": 256,
    "bootstrap_learning_rate": 5.0e-5,
    "bootstrap_sample_mode": "post_success",
    "bootstrap_followup_epochs": 10,
    "bootstrap_followup_sample_mode": "post_success_reachable",
    "bootstrap_followup_min_useful_bounces": 2,
    "bootstrap_followup_learning_rate": 3.0e-5,
}

_ENV_PRESETS["contact_frame_self_rally_v17_candidate"] = {
    **_ENV_PRESETS["contact_frame_self_rally_candidate"],
    "action_mode": "position_contact_frame_velocity_tilt_residual",
    "learning_rate": 2.0e-5,
    "n_epochs": 2,
    "clip_range": 0.08,
    "log_std_init": -2.5,
    "tracking_strike_plane_offset": 0.06,
    "tilt_action_limit": 0.006,
    "controller_velocity_feedback_gain": 0.55,
    "controller_max_velocity_step": 0.085,
    "contact_frame_base_strike_time_horizon": 0.18,
    "contact_frame_strike_hold_time": 0.08,
    "contact_frame_velocity_target_max": 3.2,
    "contact_frame_racket_vz_action_limit": 0.45,
    "contact_frame_tilt_scale_action_limit": 0.75,
    "contact_frame_trajectory_tilt_limit": (0.06, 0.06),
    "contact_frame_tilt_ramp_time": 0.45,
    "contact_frame_centering_tilt_limit": (0.045, 0.045),
    "contact_frame_action_penalty_weight": 0.10,
}

_ENV_PRESETS["contact_frame_self_rally_v18_candidate"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v17_candidate"],
    "action_mode": "position_contact_frame_velocity_tilt_lateral_residual",
    "log_std_init": -2.5,
    "scale_log_std_by_action_limit": True,
    "action_std_limit_ratio": 0.35,
    "action_std_min": 0.0015,
    "action_std_max": 0.08,
    "contact_frame_racket_xy_action_limit": 0.35,
    "tilt_action_limit": 0.008,
    "contact_frame_action_penalty_weight": 0.10,
    "post_contact_lateral_velocity_penalty_weight": 0.90,
    "contact_lateral_stability_reward_weight": 0.55,
}

_ENV_PRESETS["contact_frame_self_rally_v19_anti_low_loop"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v18_candidate"],
    "low_apex_contact_height_threshold": 0.20,
    "low_apex_contact_grace_count": 2,
    "contact_apex_under_target_penalty_weight": 1.15,
    "contact_apex_progress_reward_weight": 0.45,
    "contact_apex_recovery_progress_reward_weight": 0.25,
    "contact_apex_potential_reward_weight": 0.35,
    "contact_apex_potential_gamma": 0.99,
    "contact_apex_potential_cap": 2.0,
    "contact_lateral_stability_min_apex_ratio": 0.85,
    "stable_contact_min_apex_ratio": 0.90,
    "stable_cycle_reward_weight": 1.35,
    "stable_cycle_reward_cap": 5,
}

_ENV_PRESETS["contact_frame_self_rally_v20_boundary_brake"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v19_anti_low_loop"],
    "contact_frame_planner_contact_offset_ratio": 0.35,
    "contact_frame_planner_contact_offset_max": 0.030,
    "contact_frame_lateral_brake_gain": 1.25,
    "contact_frame_lateral_brake_max": 0.45,
    "contact_frame_lateral_brake_radius": 0.12,
    "contact_racket_lateral_velocity_penalty_weight": 0.80,
    "contact_racket_lateral_velocity_tolerance": 0.12,
    "max_contact_racket_lateral_speed_for_success": 0.35,
    "next_intercept_xy_error_penalty_weight": 1.60,
    "post_contact_lateral_velocity_penalty_weight": 1.05,
    "trajectory_error_penalty_weight": 0.95,
    "contact_apex_under_target_penalty_weight": 1.35,
    "contact_frame_low_apex_recovery_lift_gain": 0.032,
    "contact_frame_low_apex_recovery_lift_max": 0.060,
    "contact_frame_low_apex_recovery_velocity_gain": 0.38,
    "contact_frame_low_apex_recovery_velocity_max": 0.60,
}

_ENV_PRESETS["contact_frame_self_rally_v21_apex_timing_residual"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v19_anti_low_loop"],
    "action_mode": "position_contact_frame_velocity_tilt_lateral_apex_residual",
    "contact_frame_target_apex_z_action_limit": 0.08,
    "contact_frame_strike_plane_z_action_limit": 0.025,
    "contact_apex_under_target_penalty_weight": 1.25,
    "trajectory_error_penalty_weight": 0.85,
    "contact_frame_low_apex_recovery_lift_gain": 0.028,
    "contact_frame_low_apex_recovery_lift_max": 0.055,
    "contact_frame_low_apex_recovery_velocity_gain": 0.34,
    "contact_frame_low_apex_recovery_velocity_max": 0.55,
}

_ENV_PRESETS["contact_frame_self_rally_v22_low_stable_window"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v21_apex_timing_residual"],
    "low_apex_contact_height_threshold": 0.14,
    "low_apex_contact_grace_count": 3,
    "contact_apex_under_target_penalty_weight": 0.65,
    "contact_lateral_stability_min_apex_ratio": 0.70,
    "stable_contact_min_apex_ratio": 0.70,
}

_ENV_PRESETS["contact_frame_self_rally_v23_outward_timing_guard"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v22_low_stable_window"],
    "contact_racket_outward_velocity_penalty_weight": 0.85,
    "contact_racket_outward_velocity_tolerance": 0.04,
    "contact_frame_lateral_brake_gain": 0.65,
    "contact_frame_lateral_brake_max": 0.25,
    "contact_frame_lateral_brake_radius": 0.12,
    "contact_racket_lateral_velocity_penalty_weight": 0.55,
}

_ENV_PRESETS["contact_frame_self_rally_v25_long_horizon_30_bounce"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v23_outward_timing_guard"],
    "max_episode_steps": 1800,
    "stable_cycle_reward_cap": 12,
    "eval_episodes": 80,
}

_ENV_PRESETS["contact_frame_self_rally_v26_unlimited_broad_xyz"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v25_long_horizon_30_bounce"],
    "max_episode_steps": 0,
    "reset_ball_height_range": 0.0,
    "reset_ball_height_bounds": (0.24, 0.48),
    "reset_xy_range": 0.075,
    "reset_xy_sampling": "disk",
    "reset_velocity_xy_range": 0.025,
    "reset_velocity_z_range": (-0.08, 0.02),
    "eval_episodes": 60,
    "evaluation_step_limit": _UNLIMITED_EVAL_STEP_LIMIT,
}

_ENV_PRESETS["contact_frame_self_rally_v27_reachable_xy_curriculum"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v26_unlimited_broad_xyz"],
    "reset_xy_range": 0.12,
    "reset_xy_sampling": "disk",
    "reset_xy_curriculum_enabled": True,
    "reset_xy_curriculum_start": 0.075,
    "reset_xy_curriculum_end": 0.12,
    "reset_xy_curriculum_fraction": 0.85,
    "reset_xy_curriculum_update_interval": 10_000,
    "eval_episodes": 80,
}

_ENV_PRESETS["contact_frame_self_rally_v28_racket_tracking_spin"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v26_unlimited_broad_xyz"],
    "action_mode": "position_contact_frame_velocity_tilt_lateral_apex_tracking_residual",
    "reset_xy_range": 0.16,
    "reset_xy_sampling": "disk",
    "reset_xy_curriculum_enabled": True,
    "reset_xy_curriculum_start": 0.075,
    "reset_xy_curriculum_end": 0.16,
    "reset_xy_curriculum_fraction": 0.85,
    "reset_xy_curriculum_update_interval": 10_000,
    "reset_velocity_xy_range": 0.06,
    "reset_velocity_z_range": (-0.16, 0.04),
    "reset_ball_angular_velocity_range": 20.0,
    "target_offset_low": (-0.16, -0.16, -0.04),
    "target_offset_high": (0.16, 0.16, 0.13),
    "contact_frame_tracking_xy_action_limit": 0.65,
    "contact_frame_racket_xy_action_limit": 0.45,
    "controller_max_velocity_step": 0.10,
    "contact_frame_intercept_velocity_max": 1.45,
    "contact_frame_velocity_target_max": 3.6,
    "eval_episodes": 80,
}

_ENV_PRESETS["contact_frame_self_rally_v29_racket_tracking_staged_distribution"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v28_racket_tracking_spin"],
    "reset_xy_curriculum_fraction": 0.90,
    "reset_velocity_xy_curriculum_start": 0.025,
    "reset_velocity_xy_curriculum_end": 0.06,
    "reset_velocity_z_curriculum_start": (-0.08, 0.02),
    "reset_velocity_z_curriculum_end": (-0.16, 0.04),
    "reset_ball_angular_velocity_curriculum_start": 0.0,
    "reset_ball_angular_velocity_curriculum_end": 20.0,
    "contact_frame_action_penalty_weight": 0.075,
    "contact_frame_lateral_brake_gain": 0.80,
    "contact_frame_lateral_brake_max": 0.32,
    "next_intercept_xy_error_penalty_weight": 1.45,
    "post_contact_lateral_velocity_penalty_weight": 1.0,
}

_ENV_PRESETS["contact_frame_self_rally_v30_v26_wider_xy_stability"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v26_unlimited_broad_xyz"],
    "reset_xy_range": 0.10,
    "reset_xy_sampling": "disk",
    "reset_xy_curriculum_enabled": True,
    "reset_xy_curriculum_start": 0.075,
    "reset_xy_curriculum_end": 0.10,
    "reset_xy_curriculum_fraction": 0.85,
    "reset_xy_curriculum_update_interval": 10_000,
    "reset_velocity_xy_range": 0.025,
    "reset_velocity_z_range": (-0.08, 0.02),
    "reset_ball_angular_velocity_range": 0.0,
    "eval_episodes": 80,
}

_ENV_PRESETS["contact_frame_self_rally_v31_keep1_wider_xy"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v30_v26_wider_xy_stability"],
    "reset_xy_range": 0.14,
    "reset_xy_curriculum_start": 0.10,
    "reset_xy_curriculum_end": 0.14,
    "reset_xy_curriculum_fraction": 0.90,
    "target_offset_low": (-0.14, -0.14, -0.04),
    "target_offset_high": (0.14, 0.14, 0.12),
    "eval_episodes": 100,
}

_ENV_PRESETS["contact_frame_self_rally_v32_17d_v30_transfer"] = {
    **_ENV_PRESETS["contact_frame_self_rally_v30_v26_wider_xy_stability"],
    "action_mode": "position_contact_frame_velocity_tilt_lateral_apex_tracking_residual",
    "contact_frame_tracking_xy_action_limit": 0.18,
    "learning_rate": 1.0e-5,
    "n_epochs": 1,
    "clip_range": 0.05,
    "eval_episodes": 100,
}

_ENV_PRESETS["contact_frame_followthrough_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_followthrough_candidate"],
    "n_envs": 1,
    "n_steps": 512,
    "batch_size": 256,
    "learning_rate": 1.0e-5,
    "n_epochs": 1,
    "clip_range": 0.05,
    "eval_episodes": 100,
    "reset_xy_range": 0.0,
    "reset_velocity_xy_range": 0.0,
    "reset_velocity_z_range": (-0.01, 0.01),
    "bootstrap_heuristic_episodes": 120,
    "bootstrap_min_useful_bounces": 2,
    "bootstrap_max_samples": 4_000,
    "bootstrap_epochs": 50,
    "bootstrap_batch_size": 256,
    "bootstrap_learning_rate": 1.0e-4,
    "bootstrap_sample_mode": "post_success",
}

_ENV_PRESETS["contact_frame_tilt_headroom_bootstrap_candidate"] = {
    **_ENV_PRESETS["contact_frame_tilt_headroom_candidate"],
    "n_envs": 1,
    "n_steps": 512,
    "batch_size": 256,
    "learning_rate": 1.0e-5,
    "n_epochs": 1,
    "clip_range": 0.05,
    "eval_episodes": 100,
    "reset_xy_range": 0.0,
    "reset_velocity_xy_range": 0.0,
    "reset_velocity_z_range": (-0.01, 0.01),
    "bootstrap_heuristic_episodes": 120,
    "bootstrap_min_useful_bounces": 2,
    "bootstrap_max_samples": 4_000,
    "bootstrap_epochs": 50,
    "bootstrap_batch_size": 256,
    "bootstrap_learning_rate": 1.0e-4,
    "bootstrap_sample_mode": "post_success",
}


_PRESET_MANAGED_ARG_DEFAULTS: dict[str, object] = {
    "scene_path": None,
    "n_envs": 4,
    "n_steps": DEFAULT_PPO_N_STEPS,
    "batch_size": DEFAULT_PPO_BATCH_SIZE,
    "learning_rate": DEFAULT_PPO_LEARNING_RATE,
    "n_epochs": 10,
    "clip_range": 0.2,
    "eval_episodes": 5,
    "max_episode_steps": DEFAULT_MAX_EPISODE_STEPS,
    "ball_height": DEFAULT_BALL_HEIGHT,
    "reset_ball_height_range": DEFAULT_RESET_BALL_HEIGHT_RANGE,
    "reset_ball_height_bounds": None,
    "reset_xy_range": DEFAULT_RESET_XY_RANGE,
    "reset_xy_sampling": "square",
    "reset_velocity_xy_range": DEFAULT_RESET_VELOCITY_XY_RANGE,
    "reset_velocity_z_range": DEFAULT_RESET_VELOCITY_Z_RANGE,
    "reset_ball_angular_velocity_range": 0.0,
    "evaluation_step_limit": None,
    "reset_xy_curriculum_enabled": False,
    "reset_xy_curriculum_start": None,
    "reset_xy_curriculum_end": None,
    "reset_xy_curriculum_fraction": 1.0,
    "reset_xy_curriculum_update_interval": 10_000,
    "reset_velocity_xy_curriculum_start": None,
    "reset_velocity_xy_curriculum_end": None,
    "reset_velocity_z_curriculum_start": None,
    "reset_velocity_z_curriculum_end": None,
    "reset_ball_angular_velocity_curriculum_start": None,
    "reset_ball_angular_velocity_curriculum_end": None,
    "bootstrap_heuristic_episodes": 0,
    "bootstrap_min_useful_bounces": 1,
    "bootstrap_max_samples": 0,
    "bootstrap_epochs": 0,
    "bootstrap_batch_size": 256,
    "bootstrap_learning_rate": 1.0e-3,
    "bootstrap_sample_mode": "episode",
    "bootstrap_followup_epochs": 0,
    "bootstrap_followup_sample_mode": "post_success_reachable",
    "bootstrap_followup_min_useful_bounces": None,
    "bootstrap_followup_learning_rate": None,
    "action_mode": "position",
    "lateral_action_limit": None,
    "vertical_action_limit": None,
    "tilt_action_limit": None,
    "tilt_profile": "auto",
    "target_ball_height": None,
    "followup_lift_action_limit": None,
    "target_offset_low": (-0.12, -0.12, -0.04),
    "target_offset_high": (0.12, 0.12, 0.12),
    "target_tilt_limit": None,
    "strike_tilt_ramp_pitch": None,
    "strike_tilt_ramp_xy_tolerance": None,
    "post_contact_return_assist_weight": None,
    "post_contact_return_max_intercept_time": None,
    "post_contact_return_z_offset": None,
    "post_contact_return_predict_during_rise": True,
    "include_velocity_domain_observation": False,
    "include_task_phase_observation": False,
    "include_contact_context_observation": False,
    "include_next_intercept_observation": False,
    "include_desired_outgoing_velocity_observation": False,
    "desired_outgoing_xy_mode": "next_intercept",
    "keepup_target_xy_offset": None,
    "trajectory_match_reward_weight": None,
    "trajectory_error_penalty_weight": None,
    "reward_contact_quality_on_any_upward_contact": False,
    "useful_contact_return_target_xy_reward_weight": None,
    "return_target_xy_tolerance": None,
    "next_intercept_reachable_bonus_weight": None,
    "easy_next_ball_reward_weight": None,
    "require_reachable_next_intercept_for_success": False,
    "require_apex_height_window_for_success": False,
    "min_easy_next_ball_score_for_success": None,
    "gate_nonuseful_easy_next_ball_by_apex": False,
    "terminate_on_nonuseful_contact": False,
    "terminate_on_low_apex_contact": False,
    "low_apex_contact_height_threshold": None,
    "low_apex_contact_grace_count": 0,
    "followup_strike_target_tilt": None,
    "followup_strike_contact_offset_ratio": None,
    "followup_strike_contact_offset_max": None,
    "followup_strike_lift_boost": None,
    "contact_frame_base_strike_z_boost": None,
    "contact_frame_base_strike_z_offset": None,
    "contact_frame_base_strike_time_horizon": None,
    "contact_frame_base_tilt_residual": None,
    "contact_frame_apex_lift_gain": None,
    "contact_frame_apex_lift_max": None,
    "contact_frame_apex_lift_reference_velocity_z": None,
    "contact_frame_apex_lift_restitution": None,
    "contact_frame_low_apex_recovery_lift_gain": None,
    "contact_frame_low_apex_recovery_lift_max": None,
    "contact_frame_low_apex_recovery_velocity_gain": None,
    "contact_frame_low_apex_recovery_velocity_max": None,
    "contact_frame_velocity_lead_gain": None,
    "contact_frame_velocity_lead_max": None,
    "contact_frame_velocity_target_gain": None,
    "contact_frame_velocity_target_max": None,
    "contact_frame_velocity_scale_action_limit": None,
    "contact_frame_outgoing_xy_action_limit": None,
    "contact_frame_racket_vz_action_limit": None,
    "contact_frame_racket_xy_action_limit": None,
    "contact_frame_tilt_scale_action_limit": None,
    "contact_frame_target_apex_z_action_limit": None,
    "contact_frame_strike_plane_z_action_limit": None,
    "contact_frame_tracking_xy_action_limit": None,
    "contact_frame_intercept_velocity_gain": None,
    "contact_frame_intercept_velocity_max": None,
    "contact_frame_intercept_velocity_time_floor": None,
    "contact_frame_planner_enabled": False,
    "contact_frame_planner_hold_during_descent": True,
    "contact_frame_planner_min_intercept_time": None,
    "contact_frame_planner_max_intercept_time": None,
    "contact_frame_planner_target_apex_z_offset": None,
    "contact_frame_planner_contact_offset_ratio": None,
    "contact_frame_planner_contact_offset_max": None,
    "contact_frame_strike_hold_time": None,
    "contact_frame_strike_hold_min_readiness": None,
    "contact_frame_followthrough_gain": None,
    "contact_frame_followthrough_time": None,
    "contact_frame_followthrough_max": None,
    "contact_frame_lateral_brake_gain": None,
    "contact_frame_lateral_brake_max": None,
    "contact_frame_lateral_brake_radius": None,
    "contact_frame_trajectory_tilt_gain": None,
    "contact_frame_trajectory_tilt_limit": None,
    "contact_frame_trajectory_tilt_deadband": None,
    "contact_frame_tilt_ramp_time": None,
    "controller_orientation_gain": None,
    "controller_max_orientation_step": None,
    "controller_velocity_gain": None,
    "controller_velocity_feedback_gain": None,
    "controller_max_velocity_step": None,
    "next_intercept_success_radius": None,
    "easy_next_ball_xy_radius": None,
    "controller_nullspace_posture_gain": None,
    "controller_nullspace_posture_max_step": None,
    "controller_nullspace_posture_target": None,
    "controller_body_clearance_gain": None,
    "controller_body_clearance_margin": None,
    "controller_body_clearance_vertical_margin": None,
    "controller_body_clearance_max_step": None,
    "controller_body_clearance_body_names": None,
    "tracking_strike_plane_offset": None,
    "contact_frame_centering_tilt_limit": None,
    "contact_frame_centering_tilt_radius": None,
    "contact_frame_centering_tilt_deadband": None,
    "contact_frame_action_penalty_weight": None,
    "next_intercept_xy_error_penalty_weight": None,
    "post_contact_lateral_velocity_penalty_weight": None,
    "contact_xy_error_penalty_weight": None,
    "contact_racket_lateral_velocity_penalty_weight": None,
    "contact_racket_lateral_velocity_tolerance": None,
    "contact_racket_outward_velocity_penalty_weight": None,
    "contact_racket_outward_velocity_tolerance": None,
    "max_contact_racket_lateral_speed_for_success": None,
    "nonuseful_contact_penalty_weight": None,
    "contact_apex_under_target_penalty_weight": None,
    "contact_apex_progress_reward_weight": None,
    "contact_apex_recovery_progress_reward_weight": None,
    "gate_contact_apex_progress_by_easy_next_ball": False,
    "contact_apex_progress_min_easy_next_ball_score": None,
    "contact_apex_potential_reward_weight": None,
    "contact_apex_potential_gamma": None,
    "contact_apex_potential_cap": None,
    "contact_lateral_stability_reward_weight": None,
    "contact_lateral_stability_speed_tolerance": None,
    "contact_lateral_stability_xy_tolerance": None,
    "contact_lateral_stability_min_apex_ratio": None,
    "stable_contact_reward_weight": None,
    "stable_contact_min_apex_ratio": None,
    "stable_cycle_reward_weight": None,
    "stable_cycle_reward_cap": 4,
    "stable_cycle_min_easy_next_ball_score": None,
    "log_std_init": None,
    "scale_log_std_by_action_limit": False,
    "action_std_limit_ratio": None,
    "action_std_min": None,
    "action_std_max": None,
    "zero_init_action_mean": False,
}

