from __future__ import annotations

from pathlib import Path

DEFAULT_CONTROL_DT = 0.02
DEFAULT_BALL_HEIGHT = 0.50
DEFAULT_ACTION_LIMIT = 0.04
DEFAULT_MAX_EPISODE_STEPS = 600
DEFAULT_SUCCESS_VELOCITY_THRESHOLD = 0.5

DEFAULT_RESET_XY_RANGE = 0.06
DEFAULT_RESET_BALL_HEIGHT_RANGE = 0.0
DEFAULT_RESET_VELOCITY_XY_RANGE = 0.01
DEFAULT_RESET_VELOCITY_Z_RANGE = (-0.02, 0.01)

DEFAULT_TRACKING_REWARD_WEIGHT = 0.6
DEFAULT_CONTACT_BONUS = 4.0
DEFAULT_APEX_MATCH_REWARD_WEIGHT = 2.0
DEFAULT_FLOOR_PENALTY = -8.0
DEFAULT_BODY_CONTACT_PENALTY = -10.0
DEFAULT_FAILURE_PENALTY = -5.0

DEFAULT_BOUNCE_EPISODES = 5
DEFAULT_BOUNCE_MAX_STEPS = 1200

DEFAULT_PPO_TOTAL_TIMESTEPS = 20_000
DEFAULT_PPO_N_STEPS = 256
DEFAULT_PPO_BATCH_SIZE = 256
DEFAULT_PPO_LEARNING_RATE = 3.0e-4
DEFAULT_PPO_GAMMA = 0.99
DEFAULT_PPO_RUN_NAME = "pmk"
DEFAULT_PPO_POSITION_STRIKE_RUN_NAME = "pmk_s"
DEFAULT_PPO_POSITION_TILT_RUN_NAME = "pmk_t"
DEFAULT_PPO_POSITION_STRIKE_TILT_RUN_NAME = "pmk_st"
DEFAULT_PPO_POSITION_STRIKE_TILT_LIFT_RUN_NAME = "pmk_stl"
DEFAULT_PPO_POSITION_CONTACT_FRAME_RUN_NAME = "pmk_cf"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_RESIDUAL_RUN_NAME = "pmk_cfvr"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_RESIDUAL_RUN_NAME = "pmk_cfvtr"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_RESIDUAL_RUN_NAME = "pmk_cfvtlr"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_RESIDUAL_RUN_NAME = "pmk_cfvtlar"
DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_TRACKING_RESIDUAL_RUN_NAME = "pmk_cfvtlatr"

SMOKE_PPO_TOTAL_TIMESTEPS = 1_024
SMOKE_PPO_N_STEPS = 64
SMOKE_PPO_BATCH_SIZE = 64
SMOKE_PPO_RUN_NAME = "pmk_smoke"
SMOKE_PPO_POSITION_STRIKE_RUN_NAME = "pmk_s_smoke"
SMOKE_PPO_POSITION_TILT_RUN_NAME = "pmk_t_smoke"
SMOKE_PPO_POSITION_STRIKE_TILT_RUN_NAME = "pmk_st_smoke"
SMOKE_PPO_POSITION_STRIKE_TILT_LIFT_RUN_NAME = "pmk_stl_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_RUN_NAME = "pmk_cf_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_RESIDUAL_RUN_NAME = "pmk_cfvr_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_RESIDUAL_RUN_NAME = "pmk_cfvtr_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_RESIDUAL_RUN_NAME = "pmk_cfvtlr_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_RESIDUAL_RUN_NAME = "pmk_cfvtlar_smoke"
SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_TRACKING_RESIDUAL_RUN_NAME = "pmk_cfvtlatr_smoke"

LEGACY_PPO_RUN_NAMES = (
    "ppo_minimal_keepup",
    "ppo_position_tilt_keepup",
    "ppo_smoke",
    "ppo_position_tilt_smoke",
)


def default_ppo_model_candidates(ppo_runs_root: Path) -> list[Path]:
    candidate_names = (
        DEFAULT_PPO_RUN_NAME,
        DEFAULT_PPO_POSITION_STRIKE_RUN_NAME,
        DEFAULT_PPO_POSITION_TILT_RUN_NAME,
        DEFAULT_PPO_POSITION_STRIKE_TILT_RUN_NAME,
        DEFAULT_PPO_POSITION_STRIKE_TILT_LIFT_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_RESIDUAL_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_RESIDUAL_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_RESIDUAL_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_RESIDUAL_RUN_NAME,
        DEFAULT_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_TRACKING_RESIDUAL_RUN_NAME,
        SMOKE_PPO_RUN_NAME,
        SMOKE_PPO_POSITION_STRIKE_RUN_NAME,
        SMOKE_PPO_POSITION_TILT_RUN_NAME,
        SMOKE_PPO_POSITION_STRIKE_TILT_RUN_NAME,
        SMOKE_PPO_POSITION_STRIKE_TILT_LIFT_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_RESIDUAL_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_RESIDUAL_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_RESIDUAL_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_RESIDUAL_RUN_NAME,
        SMOKE_PPO_POSITION_CONTACT_FRAME_VELOCITY_TILT_LATERAL_APEX_TRACKING_RESIDUAL_RUN_NAME,
        *LEGACY_PPO_RUN_NAMES,
    )
    return [ppo_runs_root / run_name / f"{run_name}_model.zip" for run_name in candidate_names]
